#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=my_drone}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.069743
param set-default CA_ROTOR0_PY 0.084925
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.069743
param set-default CA_ROTOR1_PY -0.084925
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.069743
param set-default CA_ROTOR2_PY -0.084925
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.069743
param set-default CA_ROTOR3_PY 0.084925
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.30
param set-default NAV_DLL_ACT 2


# -------------------------------
#  Stability Softening
# -------------------------------

# Roll / Pitch position gains
param set-default MC_ROLL_P 0.7
param set-default MC_PITCH_P 0.7

# Roll / Pitch rate gains
param set-default MC_ROLLRATE_P 0.05
param set-default MC_ROLLRATE_I 0.02
param set-default MC_ROLLRATE_D 0.0003

param set-default MC_PITCHRATE_P 0.05
param set-default MC_PITCHRATE_I 0.02
param set-default MC_PITCHRATE_D 0.0003

# Yaw
param set-default MC_YAW_P 0.5
param set-default MC_YAWRATE_P 0.1
param set-default MC_YAWRATE_I 0.0

# Tilt and acceleration limits
param set-default MPC_TILTMAX_AIR 0.2
param set-default MPC_ACC_HOR_MAX 2.0
param set-default MPC_ACC_UP_MAX 2.0
param set-default MPC_ACC_DOWN_MAX 1.0
param set-default MPC_JERK_MAX 2.0

# Thrust model
param set-default MPC_THR_HOVER 0.15
param set-default THR_MDL_FAC 0.2

